import React from "react";

export default function PrivacyPolicy() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 text-gray-800">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
      <p className="mb-4">
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p className="mb-8">
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>

      {/* Interpretation and Definitions */}
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        Interpretation and Definitions
      </h2>
      <h3 className="text-xl font-semibold mt-6 mb-2">Definitions</h3>
      <p className="mb-4">
        For the purposes of this Privacy Policy:
      </p>
      <ul className="list-disc pl-6 mb-4 space-y-2">
        <li>
          <strong>Company</strong> (referred to as either "the Company", "We",
          "Us" or "Our" in this Agreement) refers to Orbitcode Innovations,
          Hyderabad, operating the app <strong>Dramachaska</strong>.
        </li>
        <li>
          <strong>Service</strong> refers to the Dramachaska mobile application.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself.
        </li>
      </ul>

      {/* Data Collection */}
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        Collecting and Using Your Personal Data
      </h2>
      <p className="mb-4">
        We may collect the following types of information when you use our
        Service:
      </p>
      <ul className="list-disc pl-6 mb-4 space-y-2">
        <li>Account details such as email address and password.</li>
        <li>Usage data including watch history, preferences, and device info.</li>
        <li>
          Information required for customer support or resolving technical
          issues.
        </li>
      </ul>

      {/* Retention */}
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        Retention of Your Personal Data
      </h2>
      <p className="mb-4">
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations, resolve disputes, and enforce our agreements and
        policies.
      </p>
      <p className="mb-4">
        <strong>
          If you request to leave our app, your personal data will be deleted
          within 30 days.
        </strong>
      </p>

      {/* Delete Data */}
      <h2 className="text-2xl font-semibold mt-8 mb-4">
        Delete Your Personal Data
      </h2>
      <p className="mb-4">
        You have the right to delete or request that We assist in deleting the
        Personal Data that We have collected about You. Our Service may give You
        the ability to delete certain information from within the Service.
      </p>
      <p className="mb-4">
        You may also contact Us to request access to, correct, or delete any
        personal information that You have provided to Us.
      </p>
      <p className="mb-4 font-semibold text-red-600">
        We delete user data within 30 days after receiving the user’s request or
        intimation to leave our app.
      </p>
      <p className="mb-4">
        Please note, however, that We may need to retain certain information
        when we have a legal obligation or lawful basis to do so.
      </p>

      {/* Contact */}
      <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
      <p className="mb-4">
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul className="list-disc pl-6 space-y-2">
        <li>By email: <a href="mailto:info@orbitcoders.com" className="text-blue-600 underline">info@orbitcoders.com</a></li>
        <li>By visiting this page on our website: https://dramachaska.com</li>
      </ul>

      <p className="mt-10 text-gray-500 text-sm">
        Last updated: September 20, 2025
      </p>
    </div>
  );
}
